<?php

namespace Domain\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TimeSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeSheetRepository extends EntityRepository
{
}